# -*- coding: utf-8 -*-
"""Build and Optimize a RAG Pipeline for Document Retrieval .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAJygeM6XVe1VxHpZxiFGnUMwCEIRbv1
"""

# Install dependencies
!pip -q install llama-index pymupdf
!pip -q install llama-index-llms-gemini llama-index-embeddings-huggingface

# Imports
import os
import fitz  # PyMuPDF

from llama_index.core import Document, Settings, VectorStoreIndex
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.response_synthesizers import get_response_synthesizer

from llama_index.llms.gemini import Gemini
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# Load my key from secrets, assert if fail, print if success
from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
assert "GOOGLE_API_KEY" in os.environ, "api key failed"
print("GOOGLE_API_KEY loaded into environment variables.")

# Upload pdf
from google.colab import files

uploaded = files.upload()  # upload the Lender Fee Worksheet PDF
pdf_path = next(iter(uploaded.keys()))
print("Using PDF:", pdf_path)

# Parse PDF
def load_pdf_as_documents(pdf_path: str) -> list[Document]:
    pdf = fitz.open(pdf_path)
    docs = []

    for i, page in enumerate(pdf):
        text = page.get_text("text").strip()
        if text:
            # store per-page so retrieval can cite page-like chunks naturally
            docs.append(Document(text=text, metadata={"page": i + 1}))
    return docs

documents = load_pdf_as_documents(pdf_path)
print("Pages loaded:", len(documents))
print("Example metadata:", documents[0].metadata if documents else None)

# Chunking configuration
# Baseline: sentence-based chunks with overlap (good general default) aka semantic chunking
chunk_size = 512
chunk_overlap = 100

splitter = SentenceSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
print("Chunking:", {"chunk_size": chunk_size, "chunk_overlap": chunk_overlap})

!pip -q install -U llama-index-llms-google-genai google-genai

import os
from llama_index.core import Settings
from llama_index.llms.google_genai import GoogleGenAI
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# Orignal code has an older model and it didn't work, and was using and old endpoint.
# If for whatever reason this cell fails, check if a new endpoint is being used or the model type, aw man

## Gemini LLM for response generation
llm = GoogleGenAI(
    model="gemini-2.5-flash",
    api_key=os.environ["GOOGLE_API_KEY"],
)

print("Models set (GoogleGenAI).")

# Embeddings (fast and solid quality, good model)
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

Settings.embed_model = embed_model
Settings.llm = llm

# Build my nodes and make the vector index

nodes = splitter.get_nodes_from_documents(documents)
print("Total chunks (nodes):", len(nodes))

index = VectorStoreIndex(nodes)
print("Index built.")

# Retrieval method: vector baseline with ranking params

top_k = 5  # retrieval depth; can be tuned

retriever = VectorIndexRetriever(index=index, similarity_top_k=top_k)

print("Retriever ready:", {"method": "vector", "top_k": top_k})

# RAG Query Engine

synthesizer = get_response_synthesizer(response_mode="compact")

query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=synthesizer,
)

print("RAG pipeline ready.")

# Debug helper, shows retrieved chunks

def debug_retrieval(q: str, k: int = None):
    k = k or top_k
    retriever.similarity_top_k = k

    results = retriever.retrieve(q)
    print("QUERY:", q)
    print("Retrieved:", len(results), "chunks\n")

    for i, r in enumerate(results, 1):
        meta = r.node.metadata
        score = getattr(r, "score", None)
        preview = r.node.text[:300].replace("\n", " ")
        print(f"{i}) score={score:.4f} page={meta.get('page')}  preview={preview}...\n")

debug_retrieval("What is the total estimated monthly payment?", k=5)

"""Example Prompts"""

!pip -q install nest_asyncio

import nest_asyncio
nest_asyncio.apply()

print("nest_asyncio applied")

prompt1 = "What is the total estimated monthly payment?"
response1 = await query_engine.aquery(prompt1)

print("User:", prompt1)
print("System:", response1)

prompt2 = "How much does the borrower pay for lender's title insurance?"
response2 = await query_engine.aquery(prompt2)

print("User:", prompt2)
print("System:", response2)